name: Convert Tamil Stories to WAV

on:
  workflow_dispatch:

jobs:
  gtts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          pip install gTTS pydub

      - name: Run TTS Script
        run: python scripts/gtts_runner.py

      # Git config as per your format
      - name: Set up Git
        run: |
          git config --global user.name "summa"
          git config --global user.email "summa@gmail.com"

      - name: Increase Git buffer size
        run: git config --global http.postBuffer 524288000

      - name: Authenticate and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git status
          git add gtts/ processed_count.txt
          git commit -m "$(date) Tamil TTS batch"
          #git push origin main --force
          for i in {1..3}; do
            git push origin main && break || sleep 60
          done

      - name: Trigger Next Batch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: gtts_process.yml
          repo: ${{ github.repository }}
          token: ${{ secrets.GH_PAT }}
